// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mokyklu_IS.Model;

namespace Mokyklu_IS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211205202252_MoreTables")]
    partial class MoreTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mokyklu_IS.Model.Administratorius", b =>
                {
                    b.Property<int>("Tabelio_nr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fk_Registracija")
                        .HasColumnType("int");

                    b.HasKey("Tabelio_nr");

                    b.HasIndex("fk_Registracija");

                    b.ToTable("Administratorius");
                });

            modelBuilder.Entity("Mokyklu_IS.Model.Dalykas", b =>
                {
                    b.Property<int>("Id_Dalykas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Ar_isplestinis")
                        .HasColumnType("bit");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Dalykas");

                    b.ToTable("Dalykas");
                });

            modelBuilder.Entity("Mokyklu_IS.Model.Klase", b =>
                {
                    b.Property<int>("Id_Klase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Metai")
                        .HasColumnType("int");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Klase");

                    b.ToTable("Klase");
                });

            modelBuilder.Entity("Mokyklu_IS.Model.Registracija", b =>
                {
                    b.Property<int>("Id_Registracija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ar_patvirtinta")
                        .HasColumnType("bit");

                    b.Property<string>("Asmens_kodas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prisijungimo_vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slaptazodis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Registracija");

                    b.ToTable("Registracija");
                });

            modelBuilder.Entity("Mokyklu_IS.Model.Susirinkimas", b =>
                {
                    b.Property<int>("Id_Susirinkimas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kabinetas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Laikas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezastis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Susirinkimas");

                    b.ToTable("Susirinkimas");
                });

            modelBuilder.Entity("Mokyklu_IS.Model.Administratorius", b =>
                {
                    b.HasOne("Mokyklu_IS.Model.Registracija", "Registracija")
                        .WithMany()
                        .HasForeignKey("fk_Registracija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
